name: Deploy To S3 & Cloudfront
on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [14.17.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.3.0
      with:
       cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
       cmd: build
    - name: Run s3-sync-action
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: dev-atarca-frontend
        AWS_REGION: 'eu-central-1'   
        SOURCE_DIR: './build' 
    - name: Run invalidate-cloudfront-action
      uses: chetan/invalidate-cloudfront-action@master
      env:
        PATHS: '/*'
        DISTRIBUTION: 'ET9E6ACKY1DUY'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}